/**
 * Seeds dataset of 200 popular global stocks
 * Includes 60 US, 30 UK, 30 European, 40 Asian, and 40 Indian NSE equities.
 */
export interface StockSeed {
  symbol: string;
  name: string;
  exchange: string;
  sector: string;
  industry: string;
  country: string;
}

export const SEED_STOCKS: StockSeed[] = [
  // --- US Equities (60) ---
  { symbol: "AAPL", name: "Apple Inc.", exchange: "NASDAQ", sector: "Technology", industry: "Consumer Electronics", country: "United States" },
  { symbol: "MSFT", name: "Microsoft Corporation", exchange: "NASDAQ", sector: "Technology", industry: "Software—Infrastructure", country: "United States" },
  { symbol: "GOOGL", name: "Alphabet Inc.", exchange: "NASDAQ", sector: "Technology", industry: "Internet Content & Information", country: "United States" },
  { symbol: "TSLA", name: "Tesla Inc.", exchange: "NASDAQ", sector: "Consumer Cyclical", industry: "Auto Manufacturers", country: "United States" },
  { symbol: "AMZN", name: "Amazon.com Inc.", exchange: "NASDAQ", sector: "Consumer Cyclical", industry: "Internet Retail", country: "United States" },
  { symbol: "NVDA", name: "NVIDIA Corporation", exchange: "NASDAQ", sector: "Technology", industry: "Semiconductors", country: "United States" },
  { symbol: "META", name: "Meta Platforms Inc.", exchange: "NASDAQ", sector: "Technology", industry: "Internet Content & Information", country: "United States" },
  { symbol: "NFLX", name: "Netflix Inc.", exchange: "NASDAQ", sector: "Communication Services", industry: "Entertainment", country: "United States" },
  { symbol: "JPM", name: "JPMorgan Chase & Co.", exchange: "NYSE", sector: "Financial", industry: "Banks—Diversified", country: "United States" },
  { symbol: "V", name: "Visa Inc.", exchange: "NYSE", sector: "Financial Services", industry: "Credit Services", country: "United States" },
  { symbol: "DIS", name: "The Walt Disney Company", exchange: "NYSE", sector: "Communication Services", industry: "Entertainment", country: "United States" },
  { symbol: "WMT", name: "Walmart Inc.", exchange: "NYSE", sector: "Consumer Defensive", industry: "Discount Stores", country: "United States" },
  { symbol: "KO", name: "The Coca-Cola Company", exchange: "NYSE", sector: "Consumer Defensive", industry: "Beverages—Non-Alcoholic", country: "United States" },
  { symbol: "PEP", name: "PepsiCo Inc.", exchange: "NASDAQ", sector: "Consumer Defensive", industry: "Beverages—Non-Alcoholic", country: "United States" },
  { symbol: "HD", name: "Home Depot Inc.", exchange: "NYSE", sector: "Consumer Cyclical", industry: "Home Improvement Retail", country: "United States" },
  { symbol: "MRK", name: "Merck & Co. Inc.", exchange: "NYSE", sector: "Healthcare", industry: "Drug Manufacturers—General", country: "United States" },
  { symbol: "PFE", name: "Pfizer Inc.", exchange: "NYSE", sector: "Healthcare", industry: "Drug Manufacturers—General", country: "United States" },
  { symbol: "JNJ", name: "Johnson & Johnson", exchange: "NYSE", sector: "Healthcare", industry: "Drug Manufacturers—General", country: "United States" },
  { symbol: "COST", name: "Costco Wholesale Corporation", exchange: "NASDAQ", sector: "Consumer Defensive", industry: "Discount Stores", country: "United States" },
  { symbol: "MCD", name: "McDonald's Corporation", exchange: "NYSE", sector: "Consumer Cyclical", industry: "Restaurants", country: "United States" },
  { symbol: "AMD", name: "Advanced Micro Devices Inc.", exchange: "NASDAQ", sector: "Technology", industry: "Semiconductors", country: "United States" },
  { symbol: "ORCL", name: "Oracle Corporation", exchange: "NYSE", sector: "Technology", industry: "Software—Infrastructure", country: "United States" },
  { symbol: "ADBE", name: "Adobe Inc.", exchange: "NASDAQ", sector: "Technology", industry: "Software—Infrastructure", country: "United States" },
  { symbol: "CRM", name: "Salesforce Inc.", exchange: "NYSE", sector: "Technology", industry: "Software—Application", country: "United States" },
  { symbol: "INTC", name: "Intel Corporation", exchange: "NASDAQ", sector: "Technology", industry: "Semiconductors", country: "United States" },
  { symbol: "CSCO", name: "Cisco Systems Inc.", exchange: "NASDAQ", sector: "Technology", industry: "Communication Equipment", country: "United States" },
  { symbol: "NKE", name: "Nike Inc.", exchange: "NYSE", sector: "Consumer Cyclical", industry: "Footwear & Accessories", country: "United States" },
  { symbol: "XOM", name: "Exxon Mobil Corporation", exchange: "NYSE", sector: "Energy", industry: "Oil & Gas Integrated", country: "United States" },
  { symbol: "CVX", name: "Chevron Corporation", exchange: "NYSE", sector: "Energy", industry: "Oil & Gas Integrated", country: "United States" },
  { symbol: "T", name: "AT&T Inc.", exchange: "NYSE", sector: "Communication Services", industry: "Telecom Services", country: "United States" },
  { symbol: "VZ", name: "Verizon Communications Inc.", exchange: "NYSE", sector: "Communication Services", industry: "Telecom Services", country: "United States" },
  { symbol: "QCOM", name: "Qualcomm Inc.", exchange: "NASDAQ", sector: "Technology", industry: "Semiconductors", country: "United States" },
  { symbol: "CAT", name: "Caterpillar Inc.", exchange: "NYSE", sector: "Industrials", industry: "Farm & Heavy Construction Machinery", country: "United States" },
  { symbol: "GS", name: "The Goldman Sachs Group Inc.", exchange: "NYSE", sector: "Financial Services", industry: "Capital Markets", country: "United States" },
  { symbol: "MS", name: "Morgan Stanley", exchange: "NYSE", sector: "Financial Services", industry: "Capital Markets", country: "United States" },
  { symbol: "UNH", name: "UnitedHealth Group Inc.", exchange: "NYSE", sector: "Healthcare", industry: "Healthcare Plans", country: "United States" },
  { symbol: "ABT", name: "Abbott Laboratories", exchange: "NYSE", sector: "Healthcare", industry: "Medical Devices", country: "United States" },
  { symbol: "LMT", name: "Lockheed Martin Corporation", exchange: "NYSE", sector: "Industrials", industry: "Aerospace & Defense", country: "United States" },
  { symbol: "BA", name: "The Boeing Company", exchange: "NYSE", sector: "Industrials", industry: "Aerospace & Defense", country: "United States" },
  { symbol: "AMGN", name: "Amgen Inc.", exchange: "NASDAQ", sector: "Healthcare", industry: "Biotechnology", country: "United States" },
  { symbol: "SBUX", name: "Starbucks Corporation", exchange: "NASDAQ", sector: "Consumer Cyclical", industry: "Restaurants", country: "United States" },
  { symbol: "PYPL", name: "PayPal Holdings Inc.", exchange: "NASDAQ", sector: "Financial Services", industry: "Credit Services", country: "United States" },
  { symbol: "TXN", name: "Texas Instruments Inc.", exchange: "NASDAQ", sector: "Technology", industry: "Semiconductors", country: "United States" },
  { symbol: "HON", name: "Honeywell International Inc.", exchange: "NASDAQ", sector: "Industrials", industry: "Conglomerates", country: "United States" },
  { symbol: "INTU", name: "Intuit Inc.", exchange: "NASDAQ", sector: "Technology", industry: "Software—Application", country: "United States" },
  { symbol: "IBM", name: "International Business Machines", exchange: "NYSE", sector: "Technology", industry: "Information Technology Services", country: "United States" },
  { symbol: "GE", name: "General Electric Company", exchange: "NYSE", sector: "Industrials", industry: "Conglomerates", country: "United States" },
  { symbol: "LOW", name: "Lowe's Companies Inc.", exchange: "NYSE", sector: "Consumer Cyclical", industry: "Home Improvement Retail", country: "United States" },
  { symbol: "ACN", name: "Accenture plc", exchange: "NYSE", sector: "Technology", industry: "Information Technology Services", country: "United States" },
  { symbol: "BKNG", name: "Booking Holdings Inc.", exchange: "NASDAQ", sector: "Consumer Cyclical", industry: "Travel Services", country: "United States" },
  { symbol: "BLK", name: "BlackRock Inc.", exchange: "NYSE", sector: "Financial Services", industry: "Asset Management", country: "United States" },
  { symbol: "DE", name: "Deere & Company", exchange: "NYSE", sector: "Industrials", industry: "Farm & Heavy Construction Machinery", country: "United States" },
  { symbol: "ISRG", name: "Intuitive Surgical Inc.", exchange: "NASDAQ", sector: "Healthcare", industry: "Medical Instruments & Supplies", country: "United States" },
  { symbol: "LRCX", name: "Lam Research Corporation", exchange: "NASDAQ", sector: "Technology", industry: "Semiconductor Equipment & Materials", country: "United States" },
  { symbol: "MDLZ", name: "Mondelēz International", exchange: "NASDAQ", sector: "Consumer Defensive", industry: "Confectioners", country: "United States" },
  { symbol: "TJX", name: "The TJX Companies Inc.", exchange: "NYSE", sector: "Consumer Cyclical", industry: "Apparel Retail", country: "United States" },
  { symbol: "REGN", name: "Regeneron Pharmaceuticals", exchange: "NASDAQ", sector: "Healthcare", industry: "Biotechnology", country: "United States" },
  { symbol: "ADP", name: "Automatic Data Processing", exchange: "NASDAQ", sector: "Industrial Services", industry: "Staffing & Employment Services", country: "United States" },
  { symbol: "MDN", name: "Moderna Inc.", exchange: "NASDAQ", sector: "Healthcare", industry: "Biotechnology", country: "United States" },
  { symbol: "UBER", name: "Uber Technologies Inc.", exchange: "NYSE", sector: "Technology", industry: "Software—Application", country: "United States" },

  // --- UK Equities (30) ---
  { symbol: "BP.L", name: "BP p.l.c.", exchange: "LSE", sector: "Energy", industry: "Oil & Gas Integrated", country: "United Kingdom" },
  { symbol: "HSBA.L", name: "HSBC Holdings plc", exchange: "LSE", sector: "Financial", industry: "Banks—Diversified", country: "United Kingdom" },
  { symbol: "AZN.L", name: "AstraZeneca plc", exchange: "LSE", sector: "Healthcare", industry: "Drug Manufacturers—General", country: "United Kingdom" },
  { symbol: "GSK.L", name: "GSK plc", exchange: "LSE", sector: "Healthcare", industry: "Drug Manufacturers—General", country: "United Kingdom" },
  { symbol: "VOD.L", name: "Vodafone Group Plc", exchange: "LSE", sector: "Communication Services", industry: "Telecom Services", country: "United Kingdom" },
  { symbol: "BARC.L", name: "Barclays PLC", exchange: "LSE", sector: "Financial Services", industry: "Banks—Diversified", country: "United Kingdom" },
  { symbol: "LLOY.L", name: "Lloyds Banking Group plc", exchange: "LSE", sector: "Financial Services", industry: "Banks—Regional", country: "United Kingdom" },
  { symbol: "TSCO.L", name: "Tesco PLC", exchange: "LSE", sector: "Consumer Defensive", industry: "Grocery Stores", country: "United Kingdom" },
  { symbol: "SHEL.L", name: "Shell plc", exchange: "LSE", sector: "Energy", industry: "Oil & Gas Integrated", country: "United Kingdom" },
  { symbol: "BATS.L", name: "British American Tobacco p.l.c.", exchange: "LSE", sector: "Consumer Defensive", industry: "Tobacco", country: "United Kingdom" },
  { symbol: "ULVR.L", name: "Unilever PLC", exchange: "LSE", sector: "Consumer Defensive", industry: "Household & Personal Products", country: "United Kingdom" },
  { symbol: "DGE.L", name: "Diageo plc", exchange: "LSE", sector: "Consumer Defensive", industry: "Beverages—Brewers", country: "United Kingdom" },
  { symbol: "RR.L", name: "Rolls-Royce Holdings plc", exchange: "LSE", sector: "Industrials", industry: "Aerospace & Defense", country: "United Kingdom" },
  { symbol: "RIO.L", name: "Rio Tinto Group", exchange: "LSE", sector: "Basic Materials", industry: "Other Industrial Metals & Mining", country: "United Kingdom" },
  { symbol: "UU.L", name: "United Utilities Group PLC", exchange: "LSE", sector: "Utilities", industry: "Utilities—Regulated Water", country: "United Kingdom" },
  { symbol: "NG.L", name: "National Grid plc", exchange: "LSE", sector: "Utilities", industry: "Utilities—Regulated Electric", country: "United Kingdom" },
  { symbol: "PRU.L", name: "Prudential plc", exchange: "LSE", sector: "Financial Services", industry: "Insurance—Life", country: "United Kingdom" },
  { symbol: "NWG.L", name: "NatWest Group plc", exchange: "LSE", sector: "Financial Services", industry: "Banks—Diversified", country: "United Kingdom" },
  { symbol: "AV.L", name: "Aviva plc", exchange: "LSE", sector: "Financial Services", industry: "Insurance—Diversified", country: "United Kingdom" },
  { symbol: "STAN.L", name: "Standard Chartered PLC", exchange: "LSE", sector: "Financial Services", industry: "Banks—Diversified", country: "United Kingdom" },
  { symbol: "REL.L", name: "RELX PLC", exchange: "LSE", sector: "Technology", industry: "Publishing", country: "United Kingdom" },
  { symbol: "WTB.L", name: "Whitbread PLC", exchange: "LSE", sector: "Consumer Cyclical", industry: "Restaurants", country: "United Kingdom" },
  { symbol: "AAL.L", name: "Anglo American plc", exchange: "LSE", sector: "Basic Materials", industry: "Other Industrial Metals & Mining", country: "United Kingdom" },
  { symbol: "GLEN.L", name: "Glencore plc", exchange: "LSE", sector: "Basic Materials", industry: "Other Industrial Metals & Mining", country: "United Kingdom" },
  { symbol: "INF.L", name: "Informa plc", exchange: "LSE", sector: "Communication Services", industry: "Publishing", country: "United Kingdom" },
  { symbol: "IAG.L", name: "International Consolidated Airlines", exchange: "LSE", sector: "Industrials", industry: "Airlines", country: "United Kingdom" },
  { symbol: "IMT.L", name: "Imperial Brands PLC", exchange: "LSE", sector: "Consumer Defensive", industry: "Tobacco", country: "United Kingdom" },
  { symbol: "HLMA.L", name: "Halma plc", exchange: "LSE", sector: "Technology", industry: "Scientific & Technical Instruments", country: "United Kingdom" },
  { symbol: "LAND.L", name: "Land Securities Group PLC", exchange: "LSE", sector: "Real Estate", industry: "REIT—Office", country: "United Kingdom" },
  { symbol: "AHT.L", name: "Ashtead Group plc", exchange: "LSE", sector: "Industrials", industry: "Rental & Leasing Services", country: "United Kingdom" },

  // --- European Equities (30) ---
  { symbol: "SAP.DE", name: "SAP SE", exchange: "XETRA", sector: "Technology", industry: "Software—Application", country: "Germany" },
  { symbol: "MBG.DE", name: "Mercedes-Benz Group AG", exchange: "XETRA", sector: "Consumer Cyclical", industry: "Auto Manufacturers", country: "Germany" },
  { symbol: "BAS.DE", name: "BASF SE", exchange: "XETRA", sector: "Basic Materials", industry: "Chemicals", country: "Germany" },
  { symbol: "BAYN.DE", name: "Bayer Aktiengesellschaft", exchange: "XETRA", sector: "Healthcare", industry: "Drug Manufacturers—General", country: "Germany" },
  { symbol: "ALV.DE", name: "Allianz SE", exchange: "XETRA", sector: "Financial Services", industry: "Insurance—Diversified", country: "Germany" },
  { symbol: "BMW.DE", name: "Bayerische Motoren Werke AG", exchange: "XETRA", sector: "Consumer Cyclical", industry: "Auto Manufacturers", country: "Germany" },
  { symbol: "DB1.DE", name: "Deutsche Börse AG", exchange: "XETRA", sector: "Financial Services", industry: "Financial Data & Stock Exchanges", country: "Germany" },
  { symbol: "DTE.DE", name: "Deutsche Telekom AG", exchange: "XETRA", sector: "Communication Services", industry: "Telecom Services", country: "Germany" },
  { symbol: "MC.PA", name: "LVMH Moët Hennessy", exchange: "Euronext Paris", sector: "Consumer Cyclical", industry: "Luxury Goods", country: "France" },
  { symbol: "OR.PA", name: "L'Oréal S.A.", exchange: "Euronext Paris", sector: "Consumer Defensive", industry: "Household & Personal Products", country: "France" },
  { symbol: "RMS.PA", name: "Hermes International SCA", exchange: "Euronext Paris", sector: "Consumer Cyclical", industry: "Luxury Goods", country: "France" },
  { symbol: "KER.PA", name: "Kering SA", exchange: "Euronext Paris", sector: "Consumer Cyclical", industry: "Luxury Goods", country: "France" },
  { symbol: "AIR.PA", name: "Airbus SE", exchange: "Euronext Paris", sector: "Industrials", industry: "Aerospace & Defense", country: "France" },
  { symbol: "TTE.PA", name: "TotalEnergies SE", exchange: "Euronext Paris", sector: "Energy", industry: "Oil & Gas Integrated", country: "France" },
  { symbol: "SAN.MC", name: "Banco Santander, S.A.", exchange: "Bolsa de Madrid", sector: "Financial Services", industry: "Banks—Diversified", country: "Spain" },
  { symbol: "BBVA.MC", name: "Banco Bilbao Vizcaya Argentaria", exchange: "Bolsa de Madrid", sector: "Financial Services", industry: "Banks—Diversified", country: "Spain" },
  { symbol: "ING.AS", name: "ING Groep N.V.", exchange: "Euronext Amsterdam", sector: "Financial Services", industry: "Banks—Diversified", country: "Netherlands" },
  { symbol: "ASML.AS", name: "ASML Holding N.V.", exchange: "Euronext Amsterdam", sector: "Technology", industry: "Semiconductor Equipment & Materials", country: "Netherlands" },
  { symbol: "NESN.SW", name: "Nestlé S.A.", exchange: "SIX Swiss Exchange", sector: "Consumer Defensive", industry: "Packaged Foods", country: "Switzerland" },
  { symbol: "ROG.SW", name: "Roche Holding AG", exchange: "SIX Swiss Exchange", sector: "Healthcare", industry: "Drug Manufacturers—General", country: "Switzerland" },
  { symbol: "NOVN.SW", name: "Novartis AG", exchange: "SIX Swiss Exchange", sector: "Healthcare", industry: "Drug Manufacturers—General", country: "Switzerland" },
  { symbol: "ADYEN.AS", name: "Adyen N.V.", exchange: "Euronext Amsterdam", sector: "Technology", industry: "Software—Infrastructure", country: "Netherlands" },
  { symbol: "SANOFI.PA", name: "Sanofi S.A.", exchange: "Euronext Paris", sector: "Healthcare", industry: "Drug Manufacturers—General", country: "France" },
  { symbol: "VOW3.DE", name: "Volkswagen AG", exchange: "XETRA", sector: "Consumer Cyclical", industry: "Auto Manufacturers", country: "Germany" },
  { symbol: "DHL.DE", name: "DHL Group", exchange: "XETRA", sector: "Industrials", industry: "Integrated Freight & Logistics", country: "Germany" },
  { symbol: "CRH.L", name: "CRH plc", exchange: "LSE", sector: "Basic Materials", industry: "Building Materials", country: "Ireland" },
  { symbol: "BNP.PA", name: "BNP Paribas SA", exchange: "Euronext Paris", sector: "Financial Services", industry: "Banks—Diversified", country: "France" },
  { symbol: "ENI.MI", name: "Eni S.p.A.", exchange: "Borsa Italiana", sector: "Energy", industry: "Oil & Gas Integrated", country: "Italy" },
  { symbol: "IBE.MC", name: "Iberdrola, S.A.", exchange: "Bolsa de Madrid", sector: "Utilities", industry: "Utilities—Regulated Electric", country: "Spain" },
  { symbol: "RWE.DE", name: "RWE AG", exchange: "XETRA", sector: "Utilities", industry: "Utilities—Diversified", country: "Germany" },

  // --- Asian Equities (40) ---
  { symbol: "9984.T", name: "SoftBank Group Corp.", exchange: "Tokyo", sector: "Financial Services", industry: "Telecom Services", country: "Japan" },
  { symbol: "7203.T", name: "Toyota Motor Corporation", exchange: "Tokyo", sector: "Consumer Cyclical", industry: "Auto Manufacturers", country: "Japan" },
  { symbol: "6758.T", name: "Sony Group Corporation", exchange: "Tokyo", sector: "Consumer Cyclical", industry: "Consumer Electronics", country: "Japan" },
  { symbol: "9983.T", name: "Fast Retailing Co. Ltd.", exchange: "Tokyo", sector: "Consumer Cyclical", industry: "Apparel Retail", country: "Japan" },
  { symbol: "8035.T", name: "Tokyo Electron Limited", exchange: "Tokyo", sector: "Technology", industry: "Semiconductor Equipment & Materials", country: "Japan" },
  { symbol: "7751.T", name: "Canon Inc.", exchange: "Tokyo", sector: "Technology", industry: "Computer Hardware", country: "Japan" },
  { symbol: "6954.T", name: "Fanuc Corporation", exchange: "Tokyo", sector: "Industrials", industry: "Industrial Machinery", country: "Japan" },
  { symbol: "7267.T", name: "Honda Motor Co., Ltd.", exchange: "Tokyo", sector: "Consumer Cyclical", industry: "Auto Manufacturers", country: "Japan" },
  { symbol: "005930.KS", name: "Samsung Electronics Co., Ltd.", exchange: "KRX", sector: "Technology", industry: "Semiconductors", country: "South Korea" },
  { symbol: "000660.KS", name: "SK Hynix Inc.", exchange: "KRX", sector: "Technology", industry: "Semiconductors", country: "South Korea" },
  { symbol: "035420.KS", name: "NAVER Corporation", exchange: "KRX", sector: "Technology", industry: "Internet Content & Information", country: "South Korea" },
  { symbol: "1299.HK", name: "AIA Group Limited", exchange: "HKEX", sector: "Financial Services", industry: "Insurance—Life", country: "Hong Kong" },
  { symbol: "0700.HK", name: "Tencent Holdings Limited", exchange: "HKEX", sector: "Technology", industry: "Internet Content & Information", country: "China" },
  { symbol: "9988.HK", name: "Alibaba Group Holding", exchange: "HKEX", sector: "Consumer Cyclical", industry: "Internet Retail", country: "China" },
  { symbol: "3690.HK", name: "Meituan", exchange: "HKEX", sector: "Consumer Cyclical", industry: "Internet Retail", country: "China" },
  { symbol: "1810.HK", name: "Xiaomi Corporation", exchange: "HKEX", sector: "Technology", industry: "Consumer Electronics", country: "China" },
  { symbol: "9618.HK", name: "JD.com Inc.", exchange: "HKEX", sector: "Consumer Cyclical", industry: "Internet Retail", country: "China" },
  { symbol: "0386.HK", name: "Sinopec Corp.", exchange: "HKEX", sector: "Energy", industry: "Oil & Gas Refining & Marketing", country: "China" },
  { symbol: "2330.TW", name: "Taiwan Semiconductor Manufacturing", exchange: "TWSE", sector: "Technology", industry: "Semiconductors", country: "Taiwan" },
  { symbol: "2454.TW", name: "MediaTek Inc.", exchange: "TWSE", sector: "Technology", industry: "Semiconductors", country: "Taiwan" },
  { symbol: "7201.T", name: "Nissan Motor Co., Ltd.", exchange: "Tokyo", sector: "Consumer Cyclical", industry: "Auto Manufacturers", country: "Japan" },
  { symbol: "6501.T", name: "Hitachi, Ltd.", exchange: "Tokyo", sector: "Industrials", industry: "Conglomerates", country: "Japan" },
  { symbol: "7974.T", name: "Nintendo Co., Ltd.", exchange: "Tokyo", sector: "Communication Services", industry: "Electronic Gaming & Multimedia", country: "Japan" },
  { symbol: "8306.T", name: "Mitsubishi UFJ Financial Group Ltd.", exchange: "Tokyo", sector: "Financial Services", industry: "Banks—Diversified", country: "Japan" },
  { symbol: "8316.T", name: "Sumitomo Mitsui Financial Group", exchange: "Tokyo", sector: "Financial Services", industry: "Banks—Diversified", country: "Japan" },
  { symbol: "9432.T", name: "Nippon Telegraph and Telephone Corp", exchange: "Tokyo", sector: "Communication Services", industry: "Telecom Services", country: "Japan" },
  { symbol: "8001.T", name: "Itochu Corporation", exchange: "Tokyo", sector: "Industrials", industry: "Conglomerates", country: "Japan" },
  { symbol: "035720.KS", name: "Kakao Corp.", exchange: "KRX", sector: "Technology", industry: "Internet Content & Information", country: "South Korea" },
  { symbol: "051910.KS", name: "LG Chem, Ltd.", exchange: "KRX", sector: "Basic Materials", industry: "Chemicals", country: "South Korea" },
  { symbol: "005380.KS", name: "Hyundai Motor Company", exchange: "KRX", sector: "Consumer Cyclical", industry: "Auto Manufacturers", country: "South Korea" },
  { symbol: "2317.TW", name: "Hon Hai Precision Industry", exchange: "TWSE", sector: "Technology", industry: "Electronic Components", country: "Taiwan" },
  { symbol: "939.HK", name: "China Construction Bank", exchange: "HKEX", sector: "Financial Services", industry: "Banks—Diversified", country: "China" },
  { symbol: "1398.HK", name: "Industrial and Commercial Bank", exchange: "HKEX", sector: "Financial Services", industry: "Banks—Diversified", country: "China" },
  { symbol: "3988.HK", name: "Bank of China Limited", exchange: "HKEX", sector: "Financial Services", industry: "Banks—Diversified", country: "China" },
  { symbol: "2318.HK", name: "Ping An Insurance Group", exchange: "HKEX", sector: "Financial Services", industry: "Insurance—Diversified", country: "China" },
  { symbol: "2628.HK", name: "China Life Insurance", exchange: "HKEX", sector: "Financial Services", industry: "Insurance—Life", country: "China" },
  { symbol: "1211.HK", name: "BYD Company Limited", exchange: "HKEX", sector: "Consumer Cyclical", industry: "Auto Manufacturers", country: "China" },
  { symbol: "0968.HK", name: "Xinyi Solar Holdings", exchange: "HKEX", sector: "Technology", industry: "Solar", country: "China" },
  { symbol: "1093.HK", name: "CSPC Pharmaceutical Group Ltd.", exchange: "HKEX", sector: "Healthcare", industry: "Drug Manufacturers—General", country: "China" },
  { symbol: "1177.HK", name: "Sino Biopharmaceutical Limited", exchange: "HKEX", sector: "Healthcare", industry: "Biotechnology", country: "China" },

  // --- Indian Equities (40) ---
  { symbol: "RELIANCE.NS", name: "Reliance Industries Limited", exchange: "NSE", sector: "Energy", industry: "Oil & Gas Integrated", country: "India" },
  { symbol: "TCS.NS", name: "Tata Consultancy Services Limited", exchange: "NSE", sector: "Technology", industry: "Information Technology Services", country: "India" },
  { symbol: "HDFCBANK.NS", name: "HDFC Bank Limited", exchange: "NSE", sector: "Financial Services", industry: "Banks—Diversified", country: "India" },
  { symbol: "INFY.NS", name: "Infosys Limited", exchange: "NSE", sector: "Technology", industry: "Information Technology Services", country: "India" },
  { symbol: "ICICIBANK.NS", name: "ICICI Bank Limited", exchange: "NSE", sector: "Financial Services", industry: "Banks—Diversified", country: "India" },
  { symbol: "HINDUNILVR.NS", name: "Hindustan Unilever Limited", exchange: "NSE", sector: "Consumer Defensive", industry: "Household & Personal Products", country: "India" },
  { symbol: "BHARTIARTL.NS", name: "Bharti Airtel Limited", exchange: "NSE", sector: "Communication Services", industry: "Telecom Services", country: "India" },
  { symbol: "ITC.NS", name: "ITC Limited", exchange: "NSE", sector: "Consumer Defensive", industry: "Tobacco", country: "India" },
  { symbol: "SBIN.NS", name: "State Bank of India", exchange: "NSE", sector: "Financial Services", industry: "Banks—Diversified", country: "India" },
  { symbol: "LTIM.NS", name: "LTIMindtree Limited", exchange: "NSE", sector: "Technology", industry: "Information Technology Services", country: "India" },
  { symbol: "LT.NS", name: "Larsen & Toubro Limited", exchange: "NSE", sector: "Industrials", industry: "Engineering & Construction", country: "India" },
  { symbol: "AXISBANK.NS", name: "Axis Bank Limited", exchange: "NSE", sector: "Financial Services", industry: "Banks—Diversified", country: "India" },
  { symbol: "BAJFINANCE.NS", name: "Bajaj Finance Limited", exchange: "NSE", sector: "Financial Services", industry: "Credit Services", country: "India" },
  { symbol: "ASIANPAINT.NS", name: "Asian Paints Limited", exchange: "NSE", sector: "Consumer Cyclical", industry: "Specialty Chemicals", country: "India" },
  { symbol: "MARUTI.NS", name: "Maruti Suzuki India Limited", exchange: "NSE", sector: "Consumer Cyclical", industry: "Auto Manufacturers", country: "India" },
  { symbol: "SUNPHARMA.NS", name: "Sun Pharmaceutical Industries", exchange: "NSE", sector: "Healthcare", industry: "Drug Manufacturers—Specialty & Generic", country: "India" },
  { symbol: "TITAN.NS", name: "Titan Company Limited", exchange: "NSE", sector: "Consumer Cyclical", industry: "Luxury Goods", country: "India" },
  { symbol: "ADANIENT.NS", name: "Adani Enterprises Limited", exchange: "NSE", sector: "Industrials", industry: "Conglomerates", country: "India" },
  { symbol: "TATASTEEL.NS", name: "Tata Steel Limited", exchange: "NSE", sector: "Basic Materials", industry: "Steel", country: "India" },
  { symbol: "TATAMOTORS.NS", name: "Tata Motors Limited", exchange: "NSE", sector: "Consumer Cyclical", industry: "Auto Manufacturers", country: "India" },
  { symbol: "KOTAKBANK.NS", name: "Kotak Mahindra Bank Limited", exchange: "NSE", sector: "Financial Services", industry: "Banks—Diversified", country: "India" },
  { symbol: "WIPRO.NS", name: "Wipro Limited", exchange: "NSE", sector: "Technology", industry: "Information Technology Services", country: "India" },
  { symbol: "TECHM.NS", name: "Tech Mahindra Limited", exchange: "NSE", sector: "Technology", industry: "Information Technology Services", country: "India" },
  { symbol: "ULTRACEMCO.NS", name: "UltraTech Cement Limited", exchange: "NSE", sector: "Basic Materials", industry: "Building Materials", country: "India" },
  { symbol: "NESTLEIND.NS", name: "Nestle India Limited", exchange: "NSE", sector: "Consumer Defensive", industry: "Packaged Foods", country: "India" },
  { symbol: "ONGC.NS", name: "Oil and Natural Gas Corporation Ltd", exchange: "NSE", sector: "Energy", industry: "Oil & Gas Exploration & Production", country: "India" },
  { symbol: "COALINDIA.NS", name: "Coal India Limited", exchange: "NSE", sector: "Energy", industry: "Other Industrial Metals & Mining", country: "India" },
  { symbol: "NTPC.NS", name: "NTPC Limited", exchange: "NSE", sector: "Utilities", industry: "Utilities—Regulated Electric", country: "India" },
  { symbol: "POWERGRID.NS", name: "Power Grid Corporation of India Ltd", exchange: "NSE", sector: "Utilities", industry: "Utilities—Regulated Electric", country: "India" },
  { symbol: "JIOFIN.NS", name: "Jio Financial Services Limited", exchange: "NSE", sector: "Financial Services", industry: "Credit Services", country: "India" },
  { symbol: "M&M.NS", name: "Mahindra & Mahindra Limited", exchange: "NSE", sector: "Consumer Cyclical", industry: "Auto Manufacturers", country: "India" },
  { symbol: "HCLTECH.NS", name: "HCL Technologies Limited", exchange: "NSE", sector: "Technology", industry: "Information Technology Services", country: "India" },
  { symbol: "BAJAJFINSV.NS", name: "Bajaj Finserv Limited", exchange: "NSE", sector: "Financial Services", industry: "Insurance—Diversified", country: "India" },
  { symbol: "ADANIPORTS.NS", name: "Adani Ports and SEZ Limited", exchange: "NSE", sector: "Industrials", industry: "Marine Shipping", country: "India" },
  { symbol: "GRASIM.NS", name: "Grasim Industries Limited", exchange: "NSE", sector: "Basic Materials", industry: "Building Materials", country: "India" },
  { symbol: "JSWSTEEL.NS", name: "JSW Steel Limited", exchange: "NSE", sector: "Basic Materials", industry: "Steel", country: "India" },
  { symbol: "HINDALCO.NS", name: "Hindalco Industries Limited", exchange: "NSE", sector: "Basic Materials", industry: "Aluminum", country: "India" },
  { symbol: "TATASTEEL.BO", name: "Tata Steel Limited (BSE)", exchange: "BSE", sector: "Basic Materials", industry: "Steel", country: "India" },
  { symbol: "SBILIFE.NS", name: "SBI Life Insurance Company Ltd", exchange: "NSE", sector: "Financial Services", industry: "Insurance—Life", country: "India" },
  { symbol: "BPCL.NS", name: "Bharat Petroleum Corporation Ltd", exchange: "NSE", sector: "Energy", industry: "Oil & Gas Refining & Marketing", country: "India" }
];
